markdown: kramdown
highlighter: rouge

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://fatliuwei.github.io/jekyllcom
help_url: https://github.com/jekyll/jekyll-help

timezone: America/Los_Angeles

collections:
  docs:
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true

name: Jekyll â€¢ Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://fatliuwei.github.io/jekyllcom/
img_url: https://raw.githubusercontent.com/fatliuwei/jekyllcom/gh-pages/


twitter:
  username: fatliuwei

logo: /img/logo-2x.png

gems:
  - jekyll-feed

exclude:
  - README.md
  - .gitignore
